import React, { useId } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { RoutesArray } from '../routes';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {RoutesArray.map((eachRoute) => (
      <>
        <Link key={eachRoute.linkName} href={eachRoute.path}><p key={eachRoute.linkName} style={{ color: 'blue', cursor: 'pointer' }}>{eachRoute.linkName}</p></Link>
        <br />
      </>
    ))}
    <Link key="SSR vs Hybration" href="/ssr-vs-hydration"><p key="SSR vs Hybration" style={{ color: 'blue', cursor: 'pointer' }}>SSR vs Hybration</p></Link>
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by
        {' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;
